# Generated by Django 5.2 on 2025-04-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_cliente_espacios_inventario_mesas_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesas',
            name='cantidadMesas',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
