# Generated by Django 5.2 on 2025-04-21 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_mesas_cantidadmesas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cliente',
            new_name='RUT',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='capacidadActual',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
