# Generated by Django 5.2 on 2025-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_espacios_capacidad_actual_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='123abc'),
        ),
    ]
