# Generated by Django 5.2 on 2025-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_cliente_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesas',
            name='cantidadActual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
