# Generated by Django 5.2 on 2025-05-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_mesas_cantidadactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadUsada', models.PositiveIntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.mesas')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.reserva')),
            ],
        ),
    ]
