# Generated by Django 5.2 on 2025-05-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_reservationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mesas',
            field=models.ManyToManyField(through='pagina.ReservationTable', to='pagina.mesas'),
        ),
    ]
