# Generated by Django 5.2 on 2025-06-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_reportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='tipo',
            field=models.CharField(),
        ),
    ]
