# Generated by Django 5.2 on 2025-06-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_alter_reportes_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(max_length=50)),
                ('asistencia', models.BooleanField(default=True)),
            ],
        ),
    ]
