# Generated by Django 5.2.4 on 2025-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_alter_product_price_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='valor_descuento',
            field=models.IntegerField(max_length=2),
        ),
    ]
